### ISSUE TITLE
No Sugar Rush And Wheels

### ISSUE THREAD

**Issue by juanroman74454811** [CyndaquilDAC/Songs-I-Made-For-Golden-Apple#1]
can you put them?

**Comment by juanroman74454811** [comment]
> cynda did not make sugar rush or wheels

i still dont have a midi of sugar rush but i have a wheels one, i will use it for a cover

**Comment by juanroman74454811** [comment]
> cynda did not make sugar rush or wheels

i also want to die

**Comment by IndigoDarkw0lf** [comment]
...

**Comment by AllenInGit** [comment]
fnf want to die to {holy i cant say ''fuck''} em off

> > cynda did not make sugar rush or wheels
> 
> i also want to die
